package services

import (
	"bytes"
	"encoding/xml"
	"fmt"
	"os"
	"time"
	"github.com/ameNZB/usenet-pipeline/config"
)

type NZB struct {
	XMLName xml.Name  `xml:"nzb"`
	Xmlns   string    `xml:"xmlns,attr"`
	Head    []NZBMeta `xml:"head>meta,omitempty"`
	Files   []NZBFile `xml:"file"`
}

type NZBMeta struct {
	Type  string `xml:"type,attr"`
	Value string `xml:",chardata"`
}

type NZBFile struct {
	Poster   string       `xml:"poster,attr"`
	Date     int64        `xml:"date,attr"`
	Subject  string       `xml:"subject,attr"`
	Groups   []string     `xml:"groups>group"`
	Segments []NZBSegment `xml:"segments>segment"`
}

// CreateNZB generates a valid NZB file from the uploaded segments.
func CreateNZB(cfg *config.Config, nzbPath string, subject string, segments []NZBSegment) error {
	data, err := CreateNZBBytes(cfg, subject, segments)
	if err != nil {
		return err
	}
	return os.WriteFile(nzbPath, data, 0644)
}

// NZBMeta provides title and request ID for NZB header metadata.
type NZBMetaInfo struct {
	Title     string
	RequestID int64
}

// CreateNZBBytes generates NZB XML as bytes for a single-file upload (legacy).
func CreateNZBBytes(cfg *config.Config, subject string, segments []NZBSegment) ([]byte, error) {
	return CreateMultiFileNZBBytes(cfg, []FileSegments{
		{FileName: subject, Segments: segments},
	}, "", NZBMetaInfo{})
}

// FileSegments groups segments by their source file.
type FileSegments struct {
	FileName string
	Segments []NZBSegment
}

// CreateMultiFileNZBBytes generates NZB XML for multiple files (raw + PAR2).
// password is stored as NZB metadata (empty string = no password).
func CreateMultiFileNZBBytes(cfg *config.Config, files []FileSegments, password string, meta NZBMetaInfo) ([]byte, error) {
	nzb := NZB{
		Xmlns: "http://www.newzbin.com/DTD/2003/nzb",
	}

	// NZB metadata.
	nzb.Head = append(nzb.Head,
		NZBMeta{Type: "x-generator", Value: cfg.GeneratorName},
	)
	if meta.Title != "" {
		nzb.Head = append(nzb.Head, NZBMeta{Type: "title", Value: meta.Title})
	}
	if meta.RequestID > 0 && cfg.SiteURL != "" {
		nzb.Head = append(nzb.Head, NZBMeta{Type: "x-info-url",
			Value: fmt.Sprintf("%s/release/%d", cfg.SiteURL, meta.RequestID)})
	}
	if password != "" {
		nzb.Head = append(nzb.Head, NZBMeta{Type: "password", Value: password})
	}

	now := time.Now().Unix()
	totalFiles := len(files)

	for i, f := range files {
		// Standard subject format: [filenum/totalfiles] - "filename" yEnc (1/totalparts) filesize
		subject := f.FileName
		if totalFiles > 1 {
			subject = f.FileName // subject per-file is set by the uploader
		}

		nzb.Files = append(nzb.Files, NZBFile{
			Poster:   cfg.NNTPPoster,
			Date:     now,
			Subject:  subject,
			Groups:   []string{cfg.NNTPGroup},
			Segments: f.Segments,
		})
		_ = i // suppress unused
	}

	var buf bytes.Buffer
	buf.WriteString(xml.Header)
	buf.WriteString(fmt.Sprintf("<!-- NZB Generated by %s -->\n", cfg.GeneratorName))

	encoder := xml.NewEncoder(&buf)
	encoder.Indent("", "  ")
	if err := encoder.Encode(nzb); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}
